- hosts: beaglebone
  remote_user: debian

  tasks:

# clone blag from github
  - git: repo=git@github.com:aztektum/blag.git
         dest=/home/debian/blag

# install OS version of virtualenv
  - apt: name=virtualenv
         state=latest
    become: yes
    become_method: sudo

# install python requirements with pip into venv
  - pip: requirements=/home/debian/blag/requirements.txt 
         virtualenv=/home/debian/blag/venv
