- hosts: blag
  remote_user: debian

  tasks:

    # clone blag from github
    - git: repo=ssh://git@github.com/aztektum/blag.git accept_hostkey=yes
           dest=/home/debian/apps/blag
           key_file=/home/debian/.ssh/ansible_key
           force=yes

    # install python requirements with pip into venv
    - pip: requirements=/home/debian/apps/blag/requirements.txt 
           virtualenv=/home/debian/apps/blag/venv

    # setup a runit job to make this work
    - file: path=/etc/sv/blag state=directory
      #when: false
      become: yes
      become_method: sudo
    
    - file: src=/home/debian/apps/blag/run dest=/etc/sv/blag/run 
            owner=debian 
            group=debian 
            state=link
      become: yes
      become_method: sudo 

    - file: path=/etc/service/blag state=directory
      become: yes
      become_method: sudo

    - file: src=/etc/sv/blag/run dest=/etc/service/blag/run
            owner=debian
            group=debian
            state=link
      become: yes
      become_method: sudo
